baseURL = "https://explore-mana.org/"
languageCode = "de-ch"
title = "Meinung, Geist, Verstand, Quelle"
disableKinds = ["taxonomy"]
ignoreErrors = ["error-disable-taxonomy"]

[params]
	siteDescription = "Einfach Wissen und News von heute für die aufgeweckte Gesellschaft von morgen."
	cloudinary_url = "https://res.cloudinary.com/chinderzytig/image/upload/"
